#!/bin/sh

GDACDATA="/mnt/c/DATA/ftp.ifremer.fr/ifremer/argo/dac/coriolis/"
WORKDATA="/mnt/c/DATA/quenching/"
SOURCE="/home/quentin/Documents/STEP2_QUENCHING/"

for mission in `cat ${SOURCE}coriolis_CHLA.list`
do

	if [ ! -d ${WORKDATA}${mission} ]
	then
		cp -fr ${GDACDATA}${mission} ${WORKDATA}${mission}
	fi

	ls -1 ${WORKDATA}${mission}"/profiles/"B*.nc | grep -v D.nc > liste_all_B
 
	#R ${WORKDATA}${mission}"/"${mission}.DARK < Quenching_correction.R
	Rscript ${SOURCE}Quenching_correction.R ${WORKDATA}${mission}"/"${mission}.DARK ${SOURCE}

done
